// Code generated by "enumer -type=CalendarType -json -text -yaml -sql"; DO NOT EDIT.

//
package calendarTypes

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const _CalendarTypeName = "GregorianJulian"

var _CalendarTypeIndex = [...]uint8{0, 9, 15}

func (i CalendarType) String() string {
	if i < 0 || i >= CalendarType(len(_CalendarTypeIndex)-1) {
		return fmt.Sprintf("CalendarType(%d)", i)
	}
	return _CalendarTypeName[_CalendarTypeIndex[i]:_CalendarTypeIndex[i+1]]
}

var _CalendarTypeValues = []CalendarType{0, 1}

var _CalendarTypeNameToValueMap = map[string]CalendarType{
	_CalendarTypeName[0:9]:  0,
	_CalendarTypeName[9:15]: 1,
}

// CalendarTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CalendarTypeString(s string) (CalendarType, error) {
	if val, ok := _CalendarTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CalendarType values", s)
}

// CalendarTypeValues returns all values of the enum
func CalendarTypeValues() []CalendarType {
	return _CalendarTypeValues
}

// IsACalendarType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CalendarType) IsACalendarType() bool {
	for _, v := range _CalendarTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CalendarType
func (i CalendarType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CalendarType
func (i *CalendarType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CalendarType should be a string, got %s", data)
	}

	var err error
	*i, err = CalendarTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CalendarType
func (i CalendarType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CalendarType
func (i *CalendarType) UnmarshalText(text []byte) error {
	var err error
	*i, err = CalendarTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CalendarType
func (i CalendarType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CalendarType
func (i *CalendarType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CalendarTypeString(s)
	return err
}

func (i CalendarType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CalendarType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CalendarTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
