// Code generated by "stringer -type=Book"; DO NOT EDIT.

package books

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Eothina-0]
	_ = x[Euchologion-1]
	_ = x[Heirmologion-2]
	_ = x[Horologion-3]
	_ = x[Katavasias-4]
	_ = x[Lectionary-5]
	_ = x[Menaion-6]
	_ = x[Octochechos-7]
	_ = x[Other-8]
	_ = x[Pentecostarion-9]
	_ = x[Psalter-10]
	_ = x[Triodion-11]
}

const _Book_name = "EothinaEuchologionHeirmologionHorologionKatavasiasLectionaryMenaionOctochechosOtherPentecostarionPsalterTriodion"

var _Book_index = [...]uint8{0, 7, 18, 30, 40, 50, 60, 67, 78, 83, 97, 104, 112}

func (i Book) String() string {
	if i < 0 || i >= Book(len(_Book_index)-1) {
		return "Book(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Book_name[_Book_index[i]:_Book_index[i+1]]
}
