// Code generated by "enumer -type=Position -json -text -yaml -sql"; DO NOT EDIT.

//
package positions

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const _PositionName = "LeftCenterRight"

var _PositionIndex = [...]uint8{0, 4, 10, 15}

func (i Position) String() string {
	if i < 0 || i >= Position(len(_PositionIndex)-1) {
		return fmt.Sprintf("Position(%d)", i)
	}
	return _PositionName[_PositionIndex[i]:_PositionIndex[i+1]]
}

var _PositionValues = []Position{0, 1, 2}

var _PositionNameToValueMap = map[string]Position{
	_PositionName[0:4]:   0,
	_PositionName[4:10]:  1,
	_PositionName[10:15]: 2,
}

// PositionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PositionString(s string) (Position, error) {
	if val, ok := _PositionNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Position values", s)
}

// PositionValues returns all values of the enum
func PositionValues() []Position {
	return _PositionValues
}

// IsAPosition returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Position) IsAPosition() bool {
	for _, v := range _PositionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Position
func (i Position) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Position
func (i *Position) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Position should be a string, got %s", data)
	}

	var err error
	*i, err = PositionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Position
func (i Position) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Position
func (i *Position) UnmarshalText(text []byte) error {
	var err error
	*i, err = PositionString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Position
func (i Position) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Position
func (i *Position) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = PositionString(s)
	return err
}

func (i Position) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Position) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := PositionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
