// Code generated by "stringer -type=DOW"; DO NOT EDIT.

package dsow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[D1-1]
	_ = x[D2-2]
	_ = x[D3-3]
	_ = x[D4-4]
	_ = x[D5-5]
	_ = x[D6-6]
	_ = x[D7-7]
}

const _DOW_name = "D1D2D3D4D5D6D7"

var _DOW_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14}

func (i DOW) String() string {
	i -= 1
	if i < 0 || i >= DOW(len(_DOW_index)-1) {
		return "DOW(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DOW_name[_DOW_index[i]:_DOW_index[i+1]]
}
